// Permanent TT shim — written once, never modified.
// Instantiates the Spade-generated gvt_core module.
// #[no_mangle(all)] in main.spade ensures the module name and port names
// match the TT interface directly, so no name mapping or unpacking is needed.
// design.v is generated by swim build in CI; a committed stub keeps lint/docs happy.

`default_nettype none

module tt_um_gerardvt_spade_poc (
    input  wire [7:0] ui_in,
    output wire [7:0] uo_out,
    input  wire [7:0] uio_in,
    output wire [7:0] uio_out,
    output wire [7:0] uio_oe,
    input  wire       ena,
    input  wire       clk,
    input  wire       rst_n
);
    gvt_core core (
        .clk    (clk),
        .rst_n  (rst_n),
        .ena    (ena),
        .ui_in  (ui_in),
        .uio_in (uio_in),
        .uo_out (uo_out),
        .uio_out(uio_out),
        .uio_oe (uio_oe)
    );
endmodule
